"""Application entry point: ``python -m meno``.

Installs a crash handler because windowed PyInstaller builds have no console;
without it an unhandled exception terminates the process with no output.
"""

from __future__ import annotations

import sys
import traceback
from types import TracebackType

from PySide6.QtGui import QIcon
from PySide6.QtWidgets import QApplication, QMessageBox

from . import config
from .ui.window import MainWindow

# Maximum number of traceback characters shown in the crash dialog.
CRASH_TEXT_LIMIT = 2000


def _install_crash_handler() -> None:
    """Route unhandled exceptions to stderr and a modal dialog."""

    def hook(exc_type: type[BaseException], exc: BaseException,
             tb: TracebackType | None) -> None:
        text = "".join(traceback.format_exception(exc_type, exc, tb))
        sys.stderr.write(text)
        QMessageBox.critical(None, "Meno crashed", text[-CRASH_TEXT_LIMIT:])

    sys.excepthook = hook


def main() -> int:
    """Start the application. Returns the Qt exit code."""
    app = QApplication(sys.argv)
    app.setApplicationName("Meno")
    # Fusion renders identically across Windows versions and themes.
    app.setStyle("Fusion")

    # Generated by tools/make_icon.py and therefore absent from a checkout
    # that has not run it. Qt's default icon is used in that case.
    icon_path = config.asset_path("meno.ico")
    if icon_path.exists():
        app.setWindowIcon(QIcon(str(icon_path)))

    _install_crash_handler()

    window = MainWindow()
    window.show()
    return app.exec()


if __name__ == "__main__":
    raise SystemExit(main())
